#+TITLE: Learning A Second Language
#+OPTIONS: toc:nil reveal_width:1200 reveal_height:1080 num:nil
#+REVEAL_ROOT: ../reveal.js
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><h3>%s</h3><h2>By %A %a</h2><h3><i>if you know how to do hello world you are sorted</i></h3><p>Press s for speaker notes</p>
#+REVEAL_THEME: black
#+REVEAL_TRANS: slide

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[top=1cm,left=3cm,right=3cm]{geometry}


* How many people have used a language other than python in the within the last decade?
#+begin_notes
If your hand has gone up then I applaud you. You have passed the second barrier
that comes to programmers (the first being learning your first language). you have broken that barrier of locking your
programming thinking into the language you are using. If you have not we will
break that barrier today and hopefully you should be more equipped to walk out
into the world of programming languages and see them not a monolith but a medium
to have a conversation with your computer.
#+end_notes

* so I presume that this code snippet will make little sense to people
#+begin_notes
so unless you are familiar with obscure academic languages then I will presume
that you can't read this code all that well

does anyone want to guess what this code does?

*give hints*
- well we can probably say that lst is a list and that function is a function
- we can probably presume that the last line calls the function function.

 other than that we will probably struggle to read more without some sort of indepth
  look at this languages semantics
#+end_notes

#+begin_src scheme
(define lst '(23 3 1 4 2 4 69 420) )

(define (function input)
  (cond
    ((or (null? input)
         (null? (cdr input)))
     input)
    (else
      (let ((pivot (car input))
            (rest (cdr input)))
        (append
          (function
            (filter (lambda (x) (< x pivot)) rest))
          (list pivot)
          (function
            (filter (lambda (x) (>= x pivot)) rest)))))))

(function lst)
#+end_src


#+ATTR_REVEAL: :frag (roll-in)
- Our Output:
 | 1 | 2 | 3 | 4 | 4 | 23 | 69 | 420 |
** the basic syntax
#+begin_notes
Syntax, whilst important, is just the basics. To draw a comparison towards learning a spoken
language its like learning the grammar without knowing a single word. That being
said, syntax is usually the easy part and should come after a while if you have
spent enough time with it. The syntax of scheme is very simple being comprised of 2 major forms in scheme.
atomic forms and s-expressions atomic forms are things like Numbers Strings
Symbols Booleans values and Characters.

s-expression's or symbolic expression's are a combinations of these atoms to form
larger structures. usually the first form after the first paren is the function
call then the next form is an argument to that function.

if you use a single quote before the start of a paren or before a symbol as
shown in the atom then it will be treated literally the first construct is how
we construct lists in scheme. the second is useful for passing around functions
and variables without having to resort to some weird string conversion hacks
#+end_notes
#+ATTR_REVEAl: :frag (roll-in)
- atoms
    #+begin_src scheme
    1 ; numbers
    "string"
    'sym ; symbols
    #t #f ;; booleans
    #\c ; harcters
    #+end_src

- s-exps
    #+begin_src scheme
    (some-function arg1 arg2 arg3...)
    (some-function '("a" "list" "of" "strings")) ; an example of a string list
    (some-function 'some-symbol)
    #+end_src

** that weird define keyword
#+begin_notes
in python there is a keyword to define functions. def you then provide it with a
name and a set of arguments so on. variables are even simpler you just name it
and use the asignment operator (also known as =) to name a value.

but notice how we use the same keyword in a very similar way.
so lets have a look at what it does.
https://www.gnu.org/software/guile/manual/html_node/Definition.html *use website*

this explains variables but not the function.. or does it. a concept in lisp is
that functions are first class citizens this means we can pass them around like
any other value. scheme takes this further by making you define them in the same
way.

here all we are doing is binding the lambda or anonymous functions to the name
func. the syntax you saw before provides a nicer syntax to do the same thing

we actually have a similar thing in python with the ~lambda~ keyword
#+end_notes

#+ATTR_REVEAl: :frag (roll-in)
- the actual way to define functions
  #+begin_src scheme
(define func
  (lambda (x) (* x 2)))

(func 2)
  #+end_src

  : 4

- python lambdas
  #+begin_src python
func = lambda x: x * 2
return func(2)
  #+end_src

  : 4

#+reveal: split

#+begin_src scheme
(define lst '(23 3 1 4 2 4 69 420) )

(define (function input)
  (cond
    ((or (null? input)
         (null? (cdr input)))
     input)
    (else
      (let ((pivot (car input))
            (rest (cdr input)))
        (append
          (function
            (filter (lambda (x) (< x pivot)) rest))
          (list pivot)
          (function
            (filter (lambda (x) (>= x pivot)) rest)))))))

(function lst)
#+end_src
** Whats cond?
#+begin_notes
cond takes multiple tests and an associated action and performs the first action
which is true. its very similar to the if elif else tree but has much less
syntax asociated with it.

notice that last element. that else clause. it looks like any other symbol or
call which is because for the most part it is. This meta programming aspect of
scheme is not something we will discuss today but if you are interested I would
recommend looking up scheme macros. in a word its a way of defining syntactic
structures like the ones we see here within the language itself
#+end_notes

#+begin_src python
x = 2
if x == 0:
    return "zero"
elif x == 1:
    return "one"
elif x == 2:
    return "two"
else:
    return "you do a lot of counting"
#+end_src

#+RESULTS:
: two

#+begin_src scheme
(define x 2)

(cond ((= x 0)
       "zero")
      ((= x 1)
       "one")
      ((= x 2)
       "two")
      (else ;; always evaluates to true
       "you do a lot of counting"))
#+end_src

#+RESULTS:
: two

#+reveal: split
#+begin_src scheme
(define lst '(23 3 1 4 2 4 69 420) )

(define (function input)
  (cond
    ((or (null? input)
         (null? (cdr input)))
     input)
    (else
      (let ((pivot (car input))
            (rest (cdr input)))
        (append
          (function
            (filter (lambda (x) (< x pivot)) rest))
          (list pivot)
          (function
            (filter (lambda (x) (>= x pivot)) rest)))))))

(function lst)
#+end_src
** or?
#+begin_notes
~Or~ takes a list of symbolic expressions that evaluate to true or false and
returns true if one of them returns true. this is like the ~Or~ keyword in python
but means you don't need to chain a lot of ~Or~ calls to check against multiple
statements

there is another function called ~And~ which will return false if any of the
functions return false. (the opposite of or like the boolean gates)
#+end_notes

#+begin_src python
return False or False or True
#+end_src

: True

#+begin_src scheme
(or #f #f #t)
#+end_src

: #t

** let
#+begin_notes
this is the final scheme construct we will be discussing

let allows us to bind values to names within the let structure itself.

this is like creating a variable in a function in python. it is only accesable
in the scope of the function.
its the same for let bindings. the variables bound can only be accessed in the body of the binding.
this is useful for a few reasons.

one it allows us to bind names to valuse without creating a variable. using
define is seen as bad form and let allows us to skirt round that.

second it scopes the bindings to a specific part meaning you can have
multiple let bindings in the same function and the names and values won't clash.
#+end_notes

#+begin_src python

def func():
    x = 5

return x
#+end_src

: x is not defined

#+begin_src scheme

(define (func)
  (let ((x 5))
    x * 2)) ;; or some other processing of x

x
#+end_src

: Unbound variable x

** the actual body of this function
#+begin_notes
now we can discuss how the function actually works
- we first check if the input is empty or the tail (every element except the
  first) of the input is empty. if so
  we return the input. something I did not discuss is that the last expression
  to be evaluated will be returned.
- if the ~Or~ function returns false then the cond moves to the else clause
- let binds the car (the first value of the array) to the name pivot and the
  name rest to the tail or everything but the first element
- we then move into the body of the let expression.
  we use the append function to append multiple arrays.
- we then apply the function to every element less than the pivot using the
  filter function.
- filter takes a function that returns true and false (called a predicate) and a
  list and keeps all of the values that make the function evaluate to true
- we then turn the pivot into a list
- and apply function to all the elements that are more than or equal to the
  pivot
  as the append function is the last thing to be evaluated in the let expression
  we will return what it evaluates
#+end_notes

#+begin_src scheme
(define lst '(23 3 1 4 2 4 69 420) )

(define (function input)
  (cond
    ((or (null? input)
         (null? (cdr input)))
     input)
    (else
      (let ((pivot (car input))
            (rest (cdr input)))
        (append
          (function
            (filter (lambda (x) (< x pivot)) rest))
          (list pivot)
          (function
            (filter (lambda (x) (>= x pivot)) rest)))))))

(function lst)
#+end_src

| 1 | 2 | 3 | 4 | 4 | 23 | 69 | 420 |

* the same code in other languages
#+begin_notes
Congrats you have picked up a little scheme! you now know the basics. tho my I
don't want you to come away with only this weird parenthasis filled language. I
want to show you the same algorithm in some other languages
#+end_notes
** haskell
#+begin_notes
Haskell is a purly functional langauge it is closer to maths in its notation
mainly because it usses a different form of computation theory called lambda
calculus

here is the quicksort algorytm in haskell.
other than the type signatures and the weird argument syntax you should be able
to understand the gist of what it does.

that input syntax is called pattern matching. is can summerise down to taking a
data structure and then checking if it conforms to a pattern (in this case the
pattern of the first element of a list and then the rest of the list) and then
binding it to a name. its like the let expression before where we bindied the
names to the car and cdr of a list
we then join the arrays using the ++ operator which works like the append
function. we append to another function call which is just recalling the
function on all the values less than the pivot
#+end_notes
#+begin_src haskell
quicksort :: Ord a => [a] -> [a] -- take any type that can be ordered
quicksort []     = [] -- if the input is an empty list return an empty list
quicksort (p:xs) = (quicksort lesser) ++ [p] ++ (quicksort greater)
    where
        lesser  = filter (< p) xs
        greater = filter (>= p) xs

-- quicksort [2,3,1]
#+end_src

| 1 | 2 | 3 |

** ruby
#+begin_notes
ruby is a purely oop langauge where everything is an object. it have influences
from python lisp smalltalk and probably some other languages. its used a lot of
for web dev tho its slowly dieing

this ruby code is very similar to the lisp one. again the last form is the one
that is returned though. return is used to exit early from a function. so we
return if arr is empty

then we destructure the input like we did in haskell or scheme. we put the first
element in the var pivot and the rest in rest. the *star tells the interpreter
to dump the rest into that rest var. we then quicksort the filtered output of
rest and use the appedn method to create the new list.
#+end_notes
#+begin_src ruby
def quicksort (arr)
  return arr if arr.empty?

  pivot, *rest = arr

  (quicksort rest.filter { |x| x < pivot }).append(
    [pivot].append(
      quicksort rest.filter { |x| x >= pivot })).flatten
end

quicksort([2,3,1])
#+end_src

| 1 | 2 | 3 |

* learning to learn
#+begin_notes
This brings me into my final point. When you want to learn a language you not
only need to learn the language but learn how to learn.

learning to learn mean you have to spend some time and find out how you pick up
knowledge.

for some its practical usage in this context a code project searching as you go
 in other words you fully embrace the stack overflow meme.
 I do this a lot when I want to learn a language. for example when I wanted to learn ruby I
implemented aqa assembly. this turned into my nea. When I wanted to learn c I
did a simliar thing with a language called brainf*uck. The other way could be to find a course.
I am learning haskell this way as it can be very theory heavy. and if you want
 to brush up on your python w3schools has a great course.

 its just a matter of finding what works for you and using it so you can cement
 that knowledge
#+end_notes
* any questions?
