baseURL = "https://jeetelongname.github.io"
languageCode = "en-gb"
title = "Jeetaditya's Blog"
theme ="hugo-ink"
paginate = 5
copyright = "copyright © Jeetaditya Chatterjee 2020-2020"
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    subtitle = "About me"
    featherIconsCDN = true
    mode = "auto"
    avatar = "https://avatars1.githubusercontent.com/u/49886197?s=460&u=c72546bdc6260023241f7a8c204b78fcca5ca20a&v=4"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Catagorys"
url = "/categories"
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jeetelongname"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "http://twitter.com/jeetaditya3"
[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
   category = "categories"
