
baseURL = "https://jeetelongname.github.io/blog/"
theme = "hugo-theme-tokiwa"
languageCode = "en-gb"
DefaultContentLanguage = "en"
copyright = "copyright © Jeetaditya Chatterjee 2020-2020"
title = "A blog about stuff"

# name = "jeetaditya chatterjee"

[params]
description = """
Hi I am Jeet. I am a Student studying computer science at UTC Reading.
I have a passion for linux, cooking and a bunch of other stuff that i will probably put on here!
"""

[menu]
    [[menu.main]]
    name = "Home"
    weight = 1
    url = "https://jeetelongname.github.io"

    [[menu.main]]
    name = "Tech Stuff"
    weight = 2
    url = "tech"

    [[menu.main]]
    name = "My Recipie"
    weight = 3
    url = "cooking"

    [[menu.main]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "about"

   [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    name = "Categories"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    url = "/categories/"
    weight = 6

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[social]
twitter="http://twitter.com/jeetaditya3"
github="http://github.com/jeetelongname"
linkedin="https://www.linkedin.com/in/jeetaditya-chatterjee-138792192/"
