baseURL = "https://www.jeetelongname.net/blog/"
languageCode = "en-gb"
title = "Jeet's Blog"
theme ="manis-hugo-theme"
paginate = 10
copyright = "&copy 2022 Jeetaditya Chatterjee"
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
   tag = "tags"
   # category = "categories"

[params]
    tagline = "Ramblings on linux and cooking (and other stuff)"
    description = "Don't expect anything anytime soon"
    themeAttrib = true
    mainSections = ["posts", "work"]
    head404 = "Sorry, I can't find what you want."
    sub404 = "Back to <a href='/'>Home</a>."
	latestCount = 5
    highlightJs = true
	highlightJsStyle = "ocean"
	highlightJsLanguages = [ "haskell", "python", "ruby", "text", "js"]
    prefix = "/blog"

	# Social Links
	email = "jeetelongname@gmail.com"
	github = "https://github.com/jeetelongname"
    # avatar = "https://avatars1.githubusercontent.com/u/49886197?s=460&u=c72546bdc6260023241f7a8c204b78fcca5ca20a&v=4"

[menu]
    [[menu.main]]
    name = "Home"
    url = ".."
    weight = 1

    [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

    [[menu.main]]
    name = "Archive"
    url = "/posts"
    weight = 3

    [[menu.main]]
    name = "Works"
    url = "/work"
    weight = 4


    [[menu.main]]
    name = "Tags"
    url = "/tags"
    # weight = 4

# [[params.social]]
# name = "Github"
# icon = "github"
# url = "https://github.com/jeetelongname"
# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "http://twitter.com/jeetaditya3"
# [[params.social]]
# name = "linkedin"
# icon = "linkedin"
# url = "https://www.linkedin.com/in/jeetaditya-chatterjee-138792192/"
# [[params.social]]
# name = "RSS"
# icon = "rss"
# url = "/blog/posts/index.xml"

