#+TITLE: The Internet
#+OPTIONS: toc:nil reveal_width:1200 reveal_height:1080 num:nil
#+REVEAL_ROOT: ../reveal.js
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><h3>%s</h3><h2>By %A %a</h2><h3><i>What would we be without this</i></h3><p>Press s for speaker notes</p>
#+REVEAL_THEME: black
#+REVEAL_TRANS: slide

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[top=1cm,left=3cm,right=3cm]{geometry}

* The Internet
#+begin_notes
The internet is a massive WAN. it has its own protocol IP with each computer
connected having there own IP Address.
Every website has there own IP address which is used to access the
#+end_notes
** IP addresses
#+begin_notes
IP or internet protocol is the main way we identify computers on the Internet.

each computer including the one your using has a unique IP address. this is used
to send data packets to your computer. Like how a mac address is used on a LAN.

the problem is this is not easy to memorise, try rememeberin 64.233.160.0 vs
google.com. to facilitate the last bit we use DNS
#+end_notes

** DNS
#+begin_notes
DNS or domain name service is the main way to resolve URL's (uniform reasource
locatiors) to actual IP addresses. what happens is that when you type in an URL
is that it will send that to a known *dns server* which will then look up the IP
address in a big table, if there is a match then it will return the IP address
to the computer that requests it, if it cannot find it then it will pass the
request onto a bigger dns server its connected too, this will be passed up the
chain untill its been found or untill the last DNS server does not have a
reccord, when that happens is an error is passed back down to the User.

when the IP is returned to the user the computer then makes the reqest and the
process continues
#+end_notes
** Hosting
#+begin_notes
We can now communicate but we need things to communicate too, Hosting is the act
performed by an internet host to run servers prividing different content. this
included

- file hosting
- web hosting
- email hosting
and so on.

This in theory should then be accessable by any device on the internet.

This is funded by a sall fee but some provide free teirs.
#+end_notes
** The Cloud
#+begin_notes
The Cloud is a generic term for services and applications accessed over the
internet. this is used in contrast to apps used on your computer.

These are usually a network of servers, some that do file storage, some that do
applications, usually in large data centers. this is

examples include
google drive
google docs
amazon web services
#+end_notes
*** Advantages
- Can be accessed on any computer, anywhere in the world
- No need to worry about updates
- Storage is usually much more flexible and can be bought for a little extra a
  month
- the hosting company is responsible for the files meaning they are usually
  backed up and safe
- easy to share
*** Disadvantages
- Requires an internet connection to access it
- Security concerns as a data center is a bigger target than your computer
- Cloud providers have a lot of control about how you use the software and can
  change pricing
** Web servers and Clients
*** Servers
#+begin_notes
Every Website is hosted on a *web server* this is a dedicated computer on the
internet that provides the website when requested. anyone can run there own
webserver but usually they go to a web hosting provider.

Anyone can write there own web server as long as they talk the same language
(usually https)
#+end_notes
*** Clients
#+begin_notes
Clients request the files from the server, when you visit a website the browser
is making a request for the website files. they are then downloaded onto your
computer and rendered
#+end_notes
