#+HUGO_BASE_DIR: ~/code/web/website/blog-hugo
#+HUGO_SECTION: posts
#+hugo_front_matter_format: yaml
* Posts
** 2am paella :cooking:cheap:easy:
:PROPERTIES:
:EXPORT_FILE_NAME: 2am-paella
:EXPORT_DATE: 2022-03-03
:END:
*** Introduction
Its 2am and your hungry, but you look in the noodle cupboard and you realise
your out of instant ramen 😱.
#+hugo: more
Here is a quick way to eat some vegetables, prep some soul
filling food and have nummies done in 20ish minutes (which is not bad for something
from scratch). This is not a traditional recipe, It kinda is similar but its not
authentic in any way, shape or form.

**** The things you will use
***** Ingredience
- rice, about a cup :: this is the base and pretty non negotiable, pasta may work in a
  pinch but it will throw off some ratios and be harder to manage.
- vegetables :: this can be anything, except maybe lettuce, here is what I
  used.
  - mushrooms of some kind.
  - an onion, I use spring onions as it also work as a garnish.
  - bell peppers
  - and sweet potatoes but again anything will work.
- spices :: I used turmeric, chilli flakes garlic and garam marsala as that's what i had
  on hand but if you had some harisa powder it would work really well here. But
  play with the flavours. Its a blank canvas.
- protein :: now this is kinda optional as the things mentioned before would
  work wonders on its own but if you have chicken pieces or something
  similar tossing them in will not hurt. That being said if you do I would try
  and keep the skin (if there is any) above the water line to help browning
  later.

***** utensils
- chopping board and knife
- serving dish :: i.e plate
- oven safe pan :: this is because we will stick it under the broiler but if you
  don't have one then this dish will still be good without broiling the top.
**** the basic method
0. preheat the broiler
1. add some oil to a pan and start to fry your protein.
   this is to give it a head start and prevent some nasty smells (boiling
   unbrowned meat smells like corpses).
2. start prepping your veg. you can do this before but this saves on a little
   time. Cut them into manageable pieces, they don't need to be clean or even as
   it will all be boiled till tender.
3. add the veg into the pan and fry it all together.
4. add in rice to toast as well as the spices before, fry till they are fragrant.
5. add water to the pan and boil till rice is soft, keep topping the water up as needed.
   - While its boiling you can basically wash up the chopping board.
6. once rice is cooked, turn off the heat and put the pan under the hot broiler,
   cook until the top is brown (this will happen quick so watch it closely).
7. eat. Optionally garnish with something green, green bit on spring onions, coriander leaves
   go nuts!

*** Finishing thoughts
This is a fun little dish that acts as a blank canvas. chuck in whatever you
have and let it simmer for a bit and your done!

* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# org-export-with-author: nil
# eval: (org-hugo-auto-export-mode)
# End:
